import re, tldextract, requests
from html import unescape

CATEGORIES = [
    "Advertising",
    "BLOCK CROSH",
    "AI Chatbots & Tools",
    "App Stores & System Updates",
    "Blogs",
    "Built-in Apps",
    "Collaboration",
    "Drugs & Alcohol",
    "Ecommerce",
    "Entertainment",
    "Gambling",
    "Games",
    "General / Education",
    "Health & Medicine",
    "Illegal, Malicious, or Hacking",
    "Religion",
    "Sexual Content",
    "Social Media",
    "Sports & Hobbies",
    "Streaming Services",
    "Weapons",
    "Uncategorized",
    "Allow only",
    "Global Block All",
]

KEYWORDS = { "BLOCK CROSH": ["chrome://crosh"],
    "AI Chatbots & Tools": [ "chatgpt",
    "openai",
 "gemini", "bard",
     "claude",
    "copilot.microsoft.com",
  "perplexity",
"writesonic",
     "midjourney",
    "jasper.ai",
    "huggingface.co",
    "stability.ai", 
    "anthropic.com",
    "runwayml.com", 
    "leonardo.ai",
    "pika.art", 
    "recraft.ai", 
    "suno.ai", 
    "elevenlabs.io", 
    "deepai.org", 
    "you.com",
    "gpt4all.io", 
    "mistral.ai", 
    "tabnine.com", 
   "deepmind",
    "cognosys.ai", 
    "character.ai",
    "blackbox.ai", 
    "krisp.ai", 
    "otter.ai", 
    "scribehow.com", 
    "descript.com", 
 "quillbot",
"grammarly",
    "replika.com",
     "writesonic",
    "notion.so",
    "tome.app",
    "beautiful.ai", 
    "heygen.com", 
    "d-id.com", 
    "synthesia.io", 
    "openrouter.ai", 
    "grok.com", 
    "pi.ai", 
    "cohere.com", 
    "ai21.com", 
    "luma.ai", 
    "play.ht", 
    "podcastle.ai", 
    "movmi.ai", 
    "flash.info", 
    "codium.ai", 
    "phind.com", 
    "together.ai", 
    "uncopilot.com", 
    "toonator.ai", 
    "genmo.ai", 
    "wondercraft.ai", "wondercraft"],
    "Social Media": [ "insta",
 "facebook",
    "meta",
   "reddit",
  "tumblr",
    "threads.net",
     "pinterest",
    "linkedin",
    "snapchat",
    "tiktok",
    "telegram",
    "x.com", "twitter",
    "discord",
    "whatsapp",
    "wechat",
    "qq.com",
    "line.me",
    "wechat",
    "weibo",
    "medium.com",
  "mastodon",
    "bluesky.social",
    "gab.com",
    "truth social",
    "parler.com",
    "gettr.com",
    "flickr.com",
    "vimeo",
  "dailymotion",
     "quora",
  "nextdoor",
    "bereal",
    "mewe",
    "fark.com",
    "imgur",
    "deviantart.com",
    "dribbble.com",
    "behance.net", 
    "ravelry.com",
    "soundcloud.com",
    "bandcamp.com", 
    "mix.com", 
    "vk.ru", 
    "odnoklassniki.ru", "odnoklassniki", "ok.ru",
    "goodreads.com",
    "cafe24.com", 
    "wattpad.com",
    "fanfiction.net", 
    "archiveofourown.org", "ao3",
    "gaiaonline.com", 
    "minoapp.com", 
    "plurk.com", 
    "ello.co", "ello",
    "flipboard.com", "flipboard",
    "peach.cool", "peach",
    "vsco.co", "vsco",
    "taringa.net", "taringa",
    "kakao.com", "kakao",
    "vero.co", "vero",
    "untappd.com", "untappd",
    "ameblo.jp", "ameblo",
    "livejournal.com", "livejournal"],
    "Games": ["roblox","fortnite","minecraft","epicgames","leagueoflegends","steam","twitch","itch.io","riot games","game"],
    "Ecommerce": [    "amazon.com", "amazon",
    "ebay.com", "ebay",
    "walmart.com", "walmart",
    "bestbuy.com", "bestbuy",
    "aliexpress.com", "aliexpress",
    "etsy.com", "etsy",
    "shopify.com", "shopify",
    "target.com", "target",
    "costco.com", "costco",
    "shein.com", "shein",
    "wayfair.com", "wayfair",
    "apple.com", "store.apple.com",
    "store.google.com",
    "nike.com",
    "adidas.com",
    "homedepot.com", "homedepot",
    "lowes.com", "lowes",
    "kohls.com", "kohls",
    "macys.com", "macys",
    "jcpenney.com", "jcpenney",
    "sears.com", "sears",
    "newegg.com", "newegg",
    "overstock.com", "overstock",
    "qvc.com", "qvc",
    "hsn.com", "hsn",
    "samsclub.com", "samsclub",
    "aldi.us", "aldi",
    "harborfreight.com", "harborfreight",
    "costplusworldmarket.com", "worldmarket",
    "bedbathandbeyond.com", "bedbathandbeyond",
    "crateandbarrel.com", "crateandbarrel",
    "ikea.com", "ikea",
    "zara.com", "zara",
    "hm.com", "hm",
    "uniqlo.com", "uniqlo",
    "primark.com", "primark",
    "urbanoutfitters.com", "urbanoutfitters",
    "victoriassecret.com", "victoriassecret",
    "sephora.com", "sephora",
    "ulta.com", "ulta",
    "glossier.com", "glossier",
    "lush.com", "lush",
    "drmartens.com", "drmartens",
    "converse.com", "converse",
    "puma.com", "puma",
    "underarmour.com", "underarmour",
    "lululemon.com", "lululemon",
    "rei.com", "rei",
    "dickssportinggoods.com", "dickssportinggoods",
    "gamestop.com", "gamestop",
    "microcenter.com", "microcenter",
    "bhphotovideo.com", "bhphotovideo",
    "adorama.com", "adorama",
    "barnesandnoble.com", "barnesandnoble",
    "chewy.com", "chewy",
    "petsmart.com", "petsmart",
    "petco.com", "petco",
    "walgreens.com", "walgreens",
    "cvs.com", "cvs",
    "riteaid.com", "riteaid",
    "instacart.com", "instacart",
    "doordash.com", "doordash store",
    "ubereats.com", "ubereats store",
    "grubhub.com", "grubhub",
    "alibaba.com", "alibaba", "temu"],
    "Streaming Services": [    "netflix.com", "netflix",
    "hulu.com", "hulu",
    "vimeo.com", "vimeo",
    "twitch.tv", "twitch",
    "soundcloud.com", "soundcloud",
    "peacocktv.com", "peacock",
    "max.com", "hbomax.com",
    "disneyplus.com", "disneyplus",
    "paramountplus.com",
    "deezer.com",
    "pandora.com",
    "audible.com",
    "amazon.com/video", "primevideo.com", "primevideo",
    "crunchyroll.com", "crunchyroll",
    "funimation.com", "funimation",
    "starz.com", "starz",
    "showtime.com", "showtime",
    "discoveryplus.com", "discoveryplus",
    "britbox.com", "britbox",
    "acorn.tv", "acorn",
    "plex.tv", "plex",
    "pluto.tv", "pluto",
    "tubi.tv", "tubi",
    "sling.com", "sling",
    "fubo.tv", "fubo",
    "roku.com", "theroku channel",
    "curiositystream.com", "curiositystream",
    "crackle.com", "crackle",
    "kanopy.com", "kanopy",
    "shudder.com", "shudder",
    "mubi.com", "mubi",
    "cineplex.com", "cineplex",
    "filmocracy.com", "filmocracy",
    "pocketcasts.com", "pocketcasts",
    "iheartradio.com", "iheartradio",
    "tidal.com", "tidal",
    "napster.com", "napster",
    "gaana.com", "gaana",
    "jiosaavn.com", "jiosaavn",
    "anghami.com", "anghami",
    "wynk.in", "wynk",
    "boomplay.com", "boomplay",
    "vevo.com", "vevo",
    "dailymotion.com", "dailymotion",
    "ustvgo.tv", "ustvgo",
    "hayu.com", "hayu",
    "sundance.tv", "sundance",
    "rifftrax.com", "rifftrax",
    "vrv.co", "vrv",
    "retrocrush.tv", "retrocrush",
    "bet.com/live-tv", "betplus",
    "nbc.com/live", "nbc",
    "cbs.com/live", "cbs",
    "abc.com/watch", "abc",
    "fox.com/live", "fox",
    "mlb.tv", "mlbtv",
    "nba.com/watch", "nbatv",
    "nhl.com/tv", "nhltv",
    "ufc.tv", "ufc",
    "wwe.com/network", "wwenetwork"],
    "Sexual Content": ["porn","xxx","xvideos","redtube","xnxx","brazzers","onlyfans","camgirl","pornhub",     "nsfw",
    "age-restricted",
    "18plus",
    "adult",
    "porn",
    "xxx",
    "erotic",
    "sex",
    "nudity",
    "nude",
    "hardcore",
    "fetish",
    "bdsm",
    "gayporn",
    "lesbianporn",
    "hentai",
    "animehentai",
    "cartoonporn",
    "camgirl",
    "camsite",
    "webcamsex",
    "escort",
    "prostitute",
    "sexwork",
    "adultvideo",
    "adultsite",
    "pornhub.com", "pornhub",
    "xvideos.com", "xvideos",
    "xhamster.com", "xhamster",
    "redtube.com", "redtube",
    "youporn.com", "youporn",
    "tube8.com", "tube8",
    "spankwire.com", "spankwire",
    "xnxx.com", "xnxx",
    "eroprofile.com", "eroprofile",
    "playboy.com", "playboy",
    "hustler.com", "hustler",
    "onlyfans.com", "onlyfans",
    "adultfriendfinder.com", "aff",
    "cam4.com", "cam4",
    "chaturbate.com", "chaturbate",
    "stripchat.com", "stripchat",
    "livejasmin.com", "livejasmin",
    "bangbros.com", "bangbros",
    "digitalplayground.com", "digitalplayground",
    "evilangel.com", "evilangel",
    "brazzers.com", "brazzers",
    "xart.com", "xart",
    "sex.com", "sex"],
    "Gambling": [    "casino",
    "sportsbook",
    "poker",
    "roulette",
    "jackpot",
    "blackjack",
    "slotmachine",
    "slots",
    "bingo",
    "lottery",
    "scratchcard",
    "scratchoff",
    "keno",
    "craps",
    "texasholdem",
    "videopoker",
    "betting",
    "wagering",
    "gamblingonline",
    "onlinecasino",
    "casinogames",
    "jackpotcity",
    "bet365.com", "bet365",
    "draftkings.com", "draftkings",
    "fanduel.com", "fanduel",
    "paddypower.com", "paddypower",
    "williamhill.com", "williamhill",
    "betfair.com", "betfair",
    "unibet.com", "unibet",
    "888casino.com", "888casino",
    "partycasino.com", "partycasino",
    "betway.com", "betway",
    "goldenpalace.com", "goldenpalace",
    "casinocom.com", "casino.com",
    "slots.lv", "slotslv",
    "ignitioncasino.eu", "ignitioncasino",
    "mansioncasino.com", "mansioncasino",
    "luckynuggetcasino.com", "luckynugget",
    "spinpalace.com", "spinpalace",
    "vegas.com", "vegas",
    "gamblingsites.com", "gamblingsites",
    "casinomeister.com", "casinomeister",
    "pokersites.com", "pokersites",
    "sportsbet.com", "sportsbet",
    "bovada.lv", "bovada",
    "betsson.com", "betsson",
    "betfred.com", "betfred",
    "coral.co.uk", "coral",
    "skybet.com", "skybet",
    "betvictor.com", "betvictor",
    "ladbrokes.com", "ladbrokes",
    "casino.org", "casinoorg",
    "pokerstars.com", "pokerstars",
    "partypoker.com", "partypoker",
    "888poker.com", "888poker"],
    "Illegal, Malicious, or Hacking": ["warez","piratebay","crack download","keygen","free movies streaming","sql injection","ddos","cheat engine"],
    "Drugs & Alcohol": ["buy weed","vape","nicotine","delta-8","kratom","bong","vodka","whiskey","winery","brewery"],
    "Collaboration": ["gmail","outlook","office 365","onedrive","teams","slack","zoom","google docs","google drive","meet.google"],
    "General / Education": ["wikipedia","news","encyclopedia","khan academy","nasa.gov",".edu"],
    "Sports & Hobbies": ["espn","nba","nfl","mlb","nhl","cars","boats","aircraft"],
    "App Stores & System Updates": ["play.google","apps.apple","microsoft store","firmware update","drivers download"],
    "Advertising": ["ads.txt","adserver","doubleclick","adchoices","advertising"],
    "Blogs": ["wordpress","blogger","wattpad","joomla","drupal","medium"],
    "Health & Medicine": ["patient portal","glucose","fitbit","apple health","pharmacy","telehealth"],
    "Religion": ["church","synagogue","mosque","bible study","quran","sermon"],
    "Weapons": ["knife","guns","rifle","ammo","silencer","tactical"],
    "Entertainment": ["tv shows","movies","anime","cartoons","jokes","memes"],
    "Built-in Apps": [  "chrome://calculator",
    "chrome://camera",
    "chrome://calendar",
    "chrome://connectivity-diagnostics",
    "chrome://crosh",
    "chrome://diagnostics",
    "chrome://downloads",
    "chrome://extensions",
    "chrome://files",
    "chrome://file-manager",
    "chrome://flags",
    "chrome://help",
    "chrome://history",
    "chrome://keyboardoverlay",
    "chrome://lock-screen",
    "chrome://media-app",
    "chrome://network",
    "chrome://notifications",
    "chrome://os-settings",
    "chrome://print",
    "chrome://settings",
    "chrome://system",
    "chrome://terms",
    "chrome://usb",
    "chrome://wallpaper",

    "chrome://accessibility",
    "chrome://app-service-internals",
    "chrome://apps",
    "chrome://autofill",
    "chrome://bluetooth",
    "chrome://bookmarks",
    "chrome://chrome-urls",
    "chrome://components",
    "chrome://discards",
    "chrome://dino",
    "chrome://family-link",
    "chrome://gpu",
    "chrome://identity-testing",
    "chrome://inspect",
    "chrome://login",
    "chrome://management",
    "chrome://media-engagement",
    "chrome://net-export",
    "chrome://network-health",
    "chrome://new-tab-page",
    "chrome://password-manager",
    "chrome://policy",
    "chrome://prefs-internals",
    "chrome://quota-internals",
    "chrome://safe-browsing",
    "chrome://sandbox",
    "chrome://serviceworker-internals",
    "chrome://signin-internals",
    "chrome://site-engagement",
    "chrome://suggestions",
    "chrome://sync-internals",
    "chrome://tab-search",
    "chrome://tracing",
    "chrome://usb-internals",
    "chrome://version",
    "chrome://webrtc-internals",
    "chrome-untrusted://camera-app",
    "chrome-untrusted://media-app",
    "chrome-untrusted://projector",
    "chrome-untrusted://family-link",
    "chrome-untrusted://diagnostics",
    "chrome-untrusted://files",
    "chrome-untrusted://crosh",
    "https://canvas.apps.chrome",
    "canvas.apps.chrome",
    "canvas.google.com"],
    # ✅ Fixed keywords for Allow only (normalized)
    "Allow only": ["canvas", "k12", "instructure.com","accounts.google.com","myaccount","accounts.google"],

}

def _fetch_html(url: str, timeout=3):
    try:
        r = requests.get(url, timeout=timeout, headers={"User-Agent":"Mozilla/5.0"})
        if r.ok and "text" in r.headers.get("Content-Type",""):
            return r.text
    except Exception:
        return ""
    return ""

def _textify(html: str):
    if not html: return ""
    txt = re.sub(r"<script[\s\S]*?</script>", " ", html, flags=re.I)
    txt = re.sub(r"<style[\s\S]*?</style>", " ", txt, flags=re.I)
    txt = re.sub(r"<[^>]+>", " ", txt)
    txt = unescape(txt)
    txt = re.sub(r"\s+", " ", txt).strip().lower()
    return txt

def classify(url: str, html: str = None):
    """
    Returns dict: {category: str, confidence: float}
    """
    if not (url or "").startswith(("http://","https://")):
        url = "https://" + (url or "")
    ext = tldextract.extract(url)
    domain = ".".join([p for p in [ext.domain, ext.suffix] if p])
    host = ".".join([p for p in [ext.subdomain, ext.domain, ext.suffix] if p if p])

    tokens = [url.lower(), host.lower(), domain.lower()]
    body = _textify(html) if html else _textify(_fetch_html(url))
    if body:
        tokens.append(body)

    scores = {c: 0 for c in CATEGORIES}
    for cat, kws in KEYWORDS.items():
        for kw in kws:
            pat = kw.lower()
            for t in tokens:
                if pat in t:
                    scores[cat] += 1

    # Special-case rules
    if any(s in domain for s in ["edu",".edu"]): scores["General / Education"] += 3
    if any(s in url for s in ["wp-login","/wp-content/"]): scores["Blogs"] += 1

    # ✅ Prioritize Allow only
    if scores["Allow only"] > 0:
        best_cat = "Allow only"
    else:
        best_cat = max(scores, key=lambda c: scores[c])
        if scores[best_cat] == 0:
            best_cat = "Uncategorized"

    total = sum(scores.values()) or 1
    conf = scores[best_cat] / total
    return {"category": best_cat, "confidence": float(conf), "domain": domain, "host": host}
